const express=require('express');const pool=require('../config/database');const {requireWriter,requireCommander}=require('../middleware/auth');
const {OperationsError,validateWorker,validateAssignment,validateOfflineCheckin,requiresManualDispatch}=require('../services/operationsWorkflow');
const router=express.Router();const tenant=req=>String(req.user.jurisdiction_id||'').trim();const actor=req=>String(req.user.id);
router.use((req,res,next)=>tenant(req)?next():res.status(403).json({error:'jurisdiction-bound identity required'}));

router.post('/workers',requireCommander,async(req,res,next)=>{const key=String(req.get('Idempotency-Key')||'').trim();if(!key)return res.status(400).json({error:'Idempotency-Key required'});let worker;try{worker=validateWorker(req.body);}catch(e){return next(e);}try{const r=await pool.query(`INSERT INTO governed_poll_workers(jurisdiction_id,idempotency_key,worker_reference,eligibility_basis,training_modules,languages,accessibility_needs,conflicts,created_by)
VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7::jsonb,$8::jsonb,$9) ON CONFLICT(jurisdiction_id,idempotency_key) DO UPDATE SET updated_at=governed_poll_workers.updated_at RETURNING *`,[tenant(req),key,worker.worker_reference,worker.eligibility_basis,JSON.stringify(worker.training_modules),JSON.stringify(worker.languages),JSON.stringify(worker.accessibility_needs),JSON.stringify(worker.conflicts),actor(req)]);res.status(201).json(r.rows[0]);}catch(e){next(e);}});

router.post('/assignments',requireWriter,async(req,res,next)=>{const key=String(req.get('Idempotency-Key')||'').trim();if(!key)return res.status(400).json({error:'Idempotency-Key required'});let a;try{a=validateAssignment(req.body);}catch(e){return next(e);}const client=await pool.connect();try{await client.query('BEGIN');const worker=await client.query('SELECT * FROM governed_poll_workers WHERE id=$1 AND jurisdiction_id=$2 FOR UPDATE',[a.worker_id,tenant(req)]);if(!worker.rows[0]){await client.query('ROLLBACK');return res.status(404).json({error:'worker not found'});}const conflicts=await client.query(`SELECT id FROM poll_assignments WHERE worker_id=$1 AND jurisdiction_id=$2 AND status!='cancelled' AND starts_at<$4 AND ends_at>$3 FOR UPDATE`,[a.worker_id,tenant(req),a.starts_at,a.ends_at]);if(conflicts.rows.length){await client.query('ROLLBACK');return res.status(409).json({error:'assignment conflict',conflicting_ids:conflicts.rows.map(x=>x.id)});}const r=await client.query(`INSERT INTO poll_assignments(jurisdiction_id,idempotency_key,worker_id,site_id,role,starts_at,ends_at,required_language,assigned_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(jurisdiction_id,idempotency_key) DO UPDATE SET updated_at=poll_assignments.updated_at RETURNING *`,[tenant(req),key,a.worker_id,a.site_id,a.role,a.starts_at,a.ends_at,a.required_language,actor(req)]);await client.query(`INSERT INTO poll_ops_events(jurisdiction_id,actor_id,subject_type,subject_id,event_type,details)VALUES($1,$2,'assignment',$3,'created',$4::jsonb)`,[tenant(req),actor(req),r.rows[0].id,JSON.stringify({site_id:a.site_id})]);await client.query('COMMIT');res.status(201).json(r.rows[0]);}catch(e){await client.query('ROLLBACK');next(e);}finally{client.release();}});

router.post('/offline-checkins',requireWriter,async(req,res,next)=>{let event;try{event=validateOfflineCheckin(req.body);}catch(e){return next(e);}try{const r=await pool.query(`INSERT INTO poll_checkin_events(jurisdiction_id,device_id,local_sequence,worker_id,site_id,event_type,recorded_at,received_by,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'pending_verification') ON CONFLICT(jurisdiction_id,device_id,local_sequence) DO UPDATE SET received_at=poll_checkin_events.received_at RETURNING *`,[tenant(req),event.device_id,event.local_sequence,event.worker_id,event.site_id,event.event_type,event.recorded_at,actor(req)]);res.status(202).json(r.rows[0]);}catch(e){next(e);}});

router.post('/incidents',requireWriter,async(req,res,next)=>{const key=String(req.get('Idempotency-Key')||'').trim(),severity=String(req.body.severity||'').toLowerCase();if(!key||!['low','moderate','high','critical'].includes(severity)||!req.body.observed_facts)return res.status(400).json({error:'Idempotency-Key, valid severity and observed_facts required'});const client=await pool.connect();try{await client.query('BEGIN');const r=await client.query(`INSERT INTO poll_ops_incidents(jurisdiction_id,idempotency_key,site_id,severity,observed_facts,reported_by,dispatch_status)VALUES($1,$2,$3,$4,$5,$6,$7)ON CONFLICT(jurisdiction_id,idempotency_key)DO UPDATE SET updated_at=poll_ops_incidents.updated_at RETURNING *`,[tenant(req),key,req.body.site_id,severity,req.body.observed_facts,actor(req),requiresManualDispatch(severity)?'manual_dispatch_required':'not_required']);if(requiresManualDispatch(severity))await client.query(`INSERT INTO poll_dispatch_outbox(jurisdiction_id,incident_id,payload)VALUES($1,$2,$3::jsonb)ON CONFLICT(incident_id)DO NOTHING`,[tenant(req),r.rows[0].id,JSON.stringify({site_id:req.body.site_id,severity})]);await client.query('COMMIT');res.status(201).json({...r.rows[0],dispatch_executed:false});}catch(e){await client.query('ROLLBACK');next(e);}finally{client.release();}});
router.use((e,req,res,next)=>e instanceof OperationsError?res.status(422).json({error:e.message,code:e.code}):next(e));module.exports=router;
